function properties(ref) {
    if (ref != null) {
      var prop;
      for (var i = 1; i <= ref.numProperties; i++) {
        prop = ref.property(i);
        alert(prop.name);
        }   
    }
}

function addColorText(layer, index, color) {
    var animator = layer.property('Text').property('Animators').addProperty('ADBE Text Animator');
    var colorProp = animator.property('Properties').addProperty('ADBE Text Fill Color');
    colorProp.setValue(color);
    var selector = animator.property('Selectors').addProperty('ADBE Text Selector');
    var advanced = selector.property('Advanced');
    advanced.property('Based On').setValue(2); // Characters
    advanced.property('Units').setValue(2); // Index
    var start = selector.property('ADBE Text Index Start').setValue(index)
    var end = selector.property('ADBE Text Index End').setValue(index+1)
}

function addLayer(indexes, color) {
    var layerText="";
    var cursor=0;
    
    
    for (var i=0; i < indexes.length; i++){
        index = indexes[i]
        for (cursor; cursor < index; cursor++) {
            layerText += "_"
        }
        layerText += text[index];
        cursor++
    }
    
    layer = comp.layers.addBoxText([width,height], layerText);
    layer.threeDLayer = true
    
    var textProp = layer.property("Source Text");
    layer.position.setValue([positionX, positionY]);
    var textDocument = textProp.value;
    textDocument.fontSize = font_size;
    textDocument.fillColor = color;
    textDocument.tracking = tracking;
    textProp.setValue(textDocument);

}


var font_size = 30;
var tracking = 700;

var positionX = 960;
var positionY = 540;

var width = 1800;
var height = 900;

var letterWidth = 22.2
var letterHeight = 36.0
var wrapLength = 22

var originX = positionX - width/2
var originY = positionY - height/2

var text = "DTHEGUERNSEYMANTOSTUBBWHYSINCEHETAKESITSOEASYTELLHIMTHATNOWIHAVEEYEDHIMCAREFULLYIMQUITECERTAINTHATHESNOMOREFITTOCOMMANDAWHALESHIPTHANASTJAGOMONKEYINFACTTELLHIMFROMMEHESABABOONHEVOWSANDDECLARESMONSIEURTHATTHEOTHERWHALETHEDRIEDONEISFARMOREDEADLYTHANTHEBLASTEDONEINFINEMONSIEURHECONJURESUSASWEVALUEOURLIVESTOCUTLOOSEFROMTHESEFISHINSTANTLYTHECAPTAINRANFORWARDANDINALOUDVOICECOMMANDEDHISCREWTODESISTFROMHOISTINGTHECUTTINGTACKLESANDATONCECASTLOOSETHECABLESANDCHAINSCONFININGTHEWHALESTOTHESHIPWHATNOWSAIDTHEGUERNSEYMANWHENTHECAPTAINHADRETURNEDTOTHEMWHYLETMESEEYESYOUMAYASWELLTELLHIMNOWTHATTHATINFACTTELLHIMIVEDIDDLEDHIMANDASIDETOHIMSELFPERHAPSSOMEBODYELSEHESAYSMONSIEURTHATHESVERYHAPPYTOHAVEBEENOFANYSERVICETOUSHEARINGTHISTHECAPTAINVOWEDTHATTHEYWERETHEGRATEFULPARTIESMEANINGHIMSELFANDMATEANDCONCLUDEDBYINVITINGSTUBBDOWNINTOHISCABINTODRINKABOTTLEOFBORDEAUXHEWANTSYOUTOTAKEAGLASSOFWINEWITHHIMSAIDTHEINTERPRETERTHANKHIMHEARTILYBUTTELLHIMITSAGAINSTMYPRINCIPLESTODRINKWITHTHEMANIVEDIDDLEDINFACTTELLHIMIMUSTGOHESAYSMONSIEURTHATHISPRINCIPLESWONTADMITOFHISDRINKINGBUTTHATIFMONSIEURWANTSTOLIVEANOTHERDAYTODRINKTHENMONSIEURHADBESTDROPALLFOURBOATSANDPULLTHESHIPAWAYFROMTHESEWHALESFORITSSOCALMTHEYWONTDRIFTBYTHISTIMESTUBBWASOVERTHESIDEANDGETTINGINTOHISBOATHAILEDTHEGUERNSEYMANTOTHISEFFECTTHATHAVINGALONGTOWLINEINHISBOATHEWOULDDOWHATHECOULDTOHELPTHEMBYPULLINGOUTTHELIGHTERWHALEOFTHETWOFROMTHESHIPSSIDEWHILETHEFRENCHMANSBOATSTHENWEREENGAGEDINTOWINGTHESHIPONEWAYSTUBBBENEVOLENTLYTOWEDAWAYATHISWHALETHEOTHERWAYOSTENTATIOUSLYSLACKINGOUTAMOSTUNUSUALLYLONGTOWLINEPRESENTLYABREEZESPRANGUPSTUBBFEIGNEDTOCASTOFFFROMTHEWHALEHOISTINGHISBOATSTHEFRENCHMANSOONINCREASEDHISDISTANCEWHILETHEPEQUODSLIDINBETWEENHIMANDSTUBBSWHALEWHEREUPONSTUBBQUICKLYPULLEDTOTHEFLOATINGBODYANDHAILINGTHEPEQUODTOGIVENOTICEOFHISINTENTIONSATONCEPROCEEDEDTOREAPTHEFRUITOFHISUNRIGHTEOUSCUNNINGSEIZINGHISSHARPBOATSPADEHECOMMENCEDANEXCAVATIONINTHEBODYALITTLEBEHINDTHESIDEFINYOUWOULDALMOSTHAVETHOUGHTHEWASDIGGINGACELLARTHEREINTHESEAANDWHENATLENGTHHISSPADESTRUCKAGAINSTTHEGAUNTRIBSITWASLIKETURNINGUPOLDROMANTILESANDPOTTERYBURIEDINFATENGLISHLOAMHISBOATSCREWWEREALLINHIGHEXCITEMENTEAGERLYHELPINGTHEIRCHIEFANDLOOKINGASANXIOUSASGOLDHUNTERSANDALLTHETIMENUMBERLESSFOWLSWEREDIVINGANDDUCKINGANDSCREAMINGANDYELLINGANDFIGHTINGAROUNDTHEMSTUBBWASBEGINNINGTOLOOKDISAPPOINTEDESPECIALLYASTHEHORRIBLENOSEGAYINCREASEDWHENSUDDENLYFROMOUTTHEVERYHEARTOFTHISPLAGUETHERESTOLEAFAINTSTREAMOFPERFUMEWHICHFLOWEDTHROUGHTHETIDEOFBADSMELLSWITHOUTBEINGABSORBEDBYITASONERIVERWILLFLOWINTOANDTHENALONGWITHANOTHERWITHOUTATALLBLENDINGWITHITFORATIMEIHAVEITIHAVEITCRIEDSTUBBWITHDELIGHTSTRIKINGSOMETHINGINTHESUBTERRANEANREGIONSAPURSEAPURSEDROPPINGHISSPADEHETHRUSTBOTHHANDSINANDDREWOUTHANDFULSOFSOMETHINGTHATLOOKEDLIKERIPEWINDSORSOAPORRICHMOTTLEDOLDCHEESEVERYUNCTUOUSANDSAVORYWITHALYOUMIGHTEASILYDENTITWITHYOURTHUMBITISOFAHUEBETWEENYELLOWANDASHCOLORANDTHISGOODFRIENDSISAMBERGRISWORTHAGOLDGUINEAANOUNCETOANYDRUGGISTSOMESIXHANDFULSWEREOBTAINEDBUTMOREWASUNAVOIDABLYLOSTINTHESEAANDSTILLMOREPERHAPSMIGHTHAVEBEENSECUREDWEREITNOTFORIMPATIENTAHABSLOUDCOMMANDTOSTUBBTODESISTANDCOMEONBOARDELSETHESHIPWOULDBIDTHEMGOODBYENOWTHISAMBERGRISISAVERYCURIOUSSUBSTANCEANDSOIMPORTANTASANARTICLEOFCOMMERCETHATINACERTAINNANTUCKETBORNCAPTAINCOFFINWASEXAMINEDATTHEBAROFTHEENGLISHHOUSEOFCOMMONSONTHATSUBJECTFORATTHATTIMEANDINDEEDUNTILACOMPARATIVELYLATEDAYTHEPRECISEORIGINOFAMBERGRISREMAINEDLIKEAMBERITSELFAPROBLEMTOTHELEARNEDTHOUGHTHEWORDAMBERGRISISBUTTHEFRENCHCOMPOUNDFORGREYAMBERYETTHETWOSUBSTANCESAREQUITEDISTINCTFORAMBERTHOUGHATTIMESFOUNDONTHESEACOASTISALSODUGUPINSOMEFARINLANDSOILSWHEREASAMBERGRISISNEVERFOUNDEXCEPTUPONTHESEABESIDESAMBERISAHARDTRANSPARENTBRITTLEODORLESSSUBSTANCEUSEDFORMOUTHPIECESTOPIPESFORBEADSANDORNAMENTSBUTAMBERGRISISSOFTWAXYANDSOHIGHLYFRAGRANTANDSPICYTHATITISLARGELYUSEDINPERFUMERYINPASTILESPRECIOUS";

app.beginUndoGroup('bible-code');
var comp = app.project.activeItem;

label = comp.layers.addBoxText([width,height], text);
label.threeDLayer = true

var textProp = label.property("Source Text");
label.position.setValue([positionX, positionY]);
var textDocument = textProp.value;
textDocument.fontSize = font_size;
textDocument.fillColor = [0, 0, 0];
textDocument.tracking = tracking;
textProp.setValue(textDocument);


// "KCIS": 665809-668287 skip:826
addColorText(label, 1045, [0.9, 0.2, 0.6645601])  //K
addColorText(label, 1871, [0.9, 0.2, 0.6645601])  //C
addColorText(label, 2697, [0.9, 0.2, 0.6645601])  //I
addColorText(label, 3523, [0.9, 0.2, 0.6645601])  //S

// "CHINA": 666870-667154 skip:71
addColorText(label, 2106, [0.2, 0.9, 0.68682307])  //C
addColorText(label, 2177, [0.2, 0.9, 0.68682307])  //H
addColorText(label, 2248, [0.2, 0.9, 0.68682307])  //I
addColorText(label, 2319, [0.2, 0.9, 0.68682307])  //N
addColorText(label, 2390, [0.2, 0.9, 0.68682307])  //A

// "ANIHC": 667070-668510 skip:360
addColorText(label, 2306, [0.06563702, 0.078259625, 0.9])  //A
addColorText(label, 2666, [0.06563702, 0.078259625, 0.9])  //N
addColorText(label, 3026, [0.06563702, 0.078259625, 0.9])  //I
addColorText(label, 3386, [0.06563702, 0.078259625, 0.9])  //H
addColorText(label, 3746, [0.06563702, 0.078259625, 0.9])  //C

// "CHINA": 666408-668128 skip:430
addColorText(label, 1644, [0.1, 0.9, 0.9])  //C
addColorText(label, 2074, [0.1, 0.9, 0.9])  //H
addColorText(label, 2504, [0.1, 0.9, 0.9])  //I
addColorText(label, 2934, [0.1, 0.9, 0.9])  //N
addColorText(label, 3364, [0.1, 0.9, 0.9])  //A

// "KCIS": 665626-666985 skip:453
addColorText(label, 862, [0.9, 0.9, 0.1])  //K
addColorText(label, 1315, [0.9, 0.9, 0.1])  //C
addColorText(label, 1768, [0.9, 0.9, 0.1])  //I
addColorText(label, 2221, [0.9, 0.9, 0.1])  //S

// "DIVOC": 664764-667176 skip:603
addColorText(label, 0, [0.5, 0.14151707, 0.5])  //D
addColorText(label, 603, [0.5, 0.14151707, 0.5])  //I
addColorText(label, 1206, [0.5, 0.14151707, 0.5])  //V
addColorText(label, 1809, [0.5, 0.14151707, 0.5])  //O
addColorText(label, 2412, [0.5, 0.14151707, 0.5])  //C

// "VIRUS": 665731-668559 skip:707
addColorText(label, 967, [0.8, 0.5, 0.1])  //V
addColorText(label, 1674, [0.8, 0.5, 0.1])  //I
addColorText(label, 2381, [0.8, 0.5, 0.1])  //R
addColorText(label, 3088, [0.8, 0.5, 0.1])  //U
addColorText(label, 3795, [0.8, 0.5, 0.1])  //S

/*
var shapeGroup = shapeLayer.property("ADBE Root Vectors Group");  // Contents

// line
var path = shapeGroup.addProperty("ADBE Vector Shape - Group"); // add a path
var pathShape = new Shape();  // create shape
pathShape.vertices = [
    [letterWidth*0.5, letterHeight*0.5],
    [letterWidth*46.5, letterHeight*7.5],
    [letterWidth*77.5, letterHeight*10.5],
    [letterWidth*26.5, letterHeight*14.5],
    [letterWidth*81.5, letterHeight*21.5],
    ]; // set the path (verticies)
pathShape.closed = false; // don't auto close the path
path.property("ADBE Vector Shape").setValue(pathShape); // put the path in the shape group
*/
app.endUndoGroup();